//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductMan.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProductMan.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password failed!.
        /// </summary>
        internal static string ChangePassword_ChangeFailed {
            get {
                return ResourceManager.GetString("ChangePassword.ChangeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully!.
        /// </summary>
        internal static string ChangePassword_ChangeOK {
            get {
                return ResourceManager.GetString("ChangePassword.ChangeOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect confirm password!.
        /// </summary>
        internal static string ChangePassword_WrongConfirmPwd {
            get {
                return ResourceManager.GetString("ChangePassword.WrongConfirmPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect new password!.
        /// </summary>
        internal static string ChangePassword_WrongNewPwd {
            get {
                return ResourceManager.GetString("ChangePassword.WrongNewPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect old password!.
        /// </summary>
        internal static string ChangePassword_WrongOldPwd {
            get {
                return ResourceManager.GetString("ChangePassword.WrongOldPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FilterPane_Filter {
            get {
                return ResourceManager.GetString("FilterPane.Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user ID or password!.
        /// </summary>
        internal static string LoginForm_InvalidIDPassword {
            get {
                return ResourceManager.GetString("LoginForm.InvalidIDPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed!.
        /// </summary>
        internal static string LoginForm_LoginFailed {
            get {
                return ResourceManager.GetString("LoginForm.LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start login....
        /// </summary>
        internal static string LoginForm_StartLogin {
            get {
                return ResourceManager.GetString("LoginForm.StartLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product failed!.
        /// </summary>
        internal static string Main_DeleteProduct_Failed {
            get {
                return ResourceManager.GetString("Main.DeleteProduct.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product successfully!.
        /// </summary>
        internal static string Main_DeleteProduct_OK {
            get {
                return ResourceManager.GetString("Main.DeleteProduct.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to delete the selected product?.
        /// </summary>
        internal static string Main_DeleteProduct_Warning {
            get {
                return ResourceManager.GetString("Main.DeleteProduct.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product stock increase failed!.
        /// </summary>
        internal static string Main_Stock_Add_Failed {
            get {
                return ResourceManager.GetString("Main.Stock.Add.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product stock increase successfully!.
        /// </summary>
        internal static string Main_Stock_Add_OK {
            get {
                return ResourceManager.GetString("Main.Stock.Add.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to increase the stock for the selected product?.
        /// </summary>
        internal static string Main_Stock_Add_Warning {
            get {
                return ResourceManager.GetString("Main.Stock.Add.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product stock reduce failed!.
        /// </summary>
        internal static string Main_Stock_Minus_Failed {
            get {
                return ResourceManager.GetString("Main.Stock.Minus.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product stock reduce successfully!.
        /// </summary>
        internal static string Main_Stock_Minus_OK {
            get {
                return ResourceManager.GetString("Main.Stock.Minus.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to reduce the stock for the selected product?.
        /// </summary>
        internal static string Main_Stock_Minus_Warning {
            get {
                return ResourceManager.GetString("Main.Stock.Minus.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name....
        /// </summary>
        internal static string NewParameter_Name_Hints {
            get {
                return ResourceManager.GetString("NewParameter.Name.Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New parameter failed!.
        /// </summary>
        internal static string NewParameter_New_Failed {
            get {
                return ResourceManager.GetString("NewParameter.New.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update parameter failed!.
        /// </summary>
        internal static string NewParameter_Update_Failed {
            get {
                return ResourceManager.GetString("NewParameter.Update.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update parameter successfully!.
        /// </summary>
        internal static string NewParameter_Update_OK {
            get {
                return ResourceManager.GetString("NewParameter.Update.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input valid parameter name!.
        /// </summary>
        internal static string NewParameter_Warning {
            get {
                return ResourceManager.GetString("NewParameter.Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product create failed.
        /// </summary>
        internal static string ProductEditor_CreateProduct_Failed {
            get {
                return ResourceManager.GetString("ProductEditor.CreateProduct.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product create successfully.
        /// </summary>
        internal static string ProductEditor_CreateProduct_OK {
            get {
                return ResourceManager.GetString("ProductEditor.CreateProduct.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name....
        /// </summary>
        internal static string ProductEditor_ProductName_Hints {
            get {
                return ResourceManager.GetString("ProductEditor.ProductName.Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity....
        /// </summary>
        internal static string ProductEditor_Quantity_Hints {
            get {
                return ResourceManager.GetString("ProductEditor.Quantity.Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product info update failed.
        /// </summary>
        internal static string ProductEditor_UpdateProduct_Failed {
            get {
                return ResourceManager.GetString("ProductEditor.UpdateProduct.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product info update successfully.
        /// </summary>
        internal static string ProductEditor_UpdateProduct_OK {
            get {
                return ResourceManager.GetString("ProductEditor.UpdateProduct.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight....
        /// </summary>
        internal static string ProductEditor_Weight_Hints {
            get {
                return ResourceManager.GetString("ProductEditor.Weight.Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string ProductPane_Caption {
            get {
                return ResourceManager.GetString("ProductPane.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string ProductPane_Category {
            get {
                return ResourceManager.GetString("ProductPane.Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string ProductPane_Color {
            get {
                return ResourceManager.GetString("ProductPane.Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafts.
        /// </summary>
        internal static string ProductPane_Crafts {
            get {
                return ResourceManager.GetString("ProductPane.Crafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        internal static string ProductPane_CreateDate {
            get {
                return ResourceManager.GetString("ProductPane.CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        internal static string ProductPane_LastMonth {
            get {
                return ResourceManager.GetString("ProductPane.LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        internal static string ProductPane_LastWeek {
            get {
                return ResourceManager.GetString("ProductPane.LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string ProductPane_Material {
            get {
                return ResourceManager.GetString("ProductPane.Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        internal static string ProductPane_ModifiedDate {
            get {
                return ResourceManager.GetString("ProductPane.ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        internal static string ProductPane_Older {
            get {
                return ResourceManager.GetString("ProductPane.Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        internal static string ProductPane_Origin {
            get {
                return ResourceManager.GetString("ProductPane.Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        internal static string ProductPane_ProductID {
            get {
                return ResourceManager.GetString("ProductPane.ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Date.
        /// </summary>
        internal static string ProductPane_ProductionDate {
            get {
                return ResourceManager.GetString("ProductPane.ProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string ProductPane_ProductName {
            get {
                return ResourceManager.GetString("ProductPane.ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string ProductPane_Remark {
            get {
                return ResourceManager.GetString("ProductPane.Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ProductPane_Search {
            get {
                return ResourceManager.GetString("ProductPane.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input keywords separated using SPACE for OR while &quot;+&quot; for AND....
        /// </summary>
        internal static string ProductPane_SearchHints {
            get {
                return ResourceManager.GetString("ProductPane.SearchHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spec.
        /// </summary>
        internal static string ProductPane_Spec {
            get {
                return ResourceManager.GetString("ProductPane.Spec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ProductPane_Status {
            get {
                return ResourceManager.GetString("ProductPane.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        internal static string ProductPane_Stock {
            get {
                return ResourceManager.GetString("ProductPane.Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string ProductPane_Style {
            get {
                return ResourceManager.GetString("ProductPane.Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category.
        /// </summary>
        internal static string ProductPane_SubCategory {
            get {
                return ResourceManager.GetString("ProductPane.SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        internal static string ProductPane_ThisMonth {
            get {
                return ResourceManager.GetString("ProductPane.ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        internal static string ProductPane_ThisWeek {
            get {
                return ResourceManager.GetString("ProductPane.ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string ProductPane_Today {
            get {
                return ResourceManager.GetString("ProductPane.Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string ProductPane_Yesterday {
            get {
                return ResourceManager.GetString("ProductPane.Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string SearchPane_All {
            get {
                return ResourceManager.GetString("SearchPane.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing product manager....
        /// </summary>
        internal static string SplashScreen_Initial {
            get {
                return ResourceManager.GetString("SplashScreen.Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing login....
        /// </summary>
        internal static string SplashScreen_InitialLogin {
            get {
                return ResourceManager.GetString("SplashScreen.InitialLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading products....
        /// </summary>
        internal static string SplashScreen_LoadProducts {
            get {
                return ResourceManager.GetString("SplashScreen.LoadProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing products....
        /// </summary>
        internal static string SplashScreen_PrepareProducts {
            get {
                return ResourceManager.GetString("SplashScreen.PrepareProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting product manager....
        /// </summary>
        internal static string SplashScreen_Startup {
            get {
                return ResourceManager.GetString("SplashScreen.Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid stock value!.
        /// </summary>
        internal static string Stock_InvalidStock {
            get {
                return ResourceManager.GetString("Stock.InvalidStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduced Stock: .
        /// </summary>
        internal static string Stock_ReduceStock {
            get {
                return ResourceManager.GetString("Stock.ReduceStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid full name!.
        /// </summary>
        internal static string UserForm_InvalidFullName {
            get {
                return ResourceManager.GetString("UserForm.InvalidFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name!.
        /// </summary>
        internal static string UserForm_InvalidUserName {
            get {
                return ResourceManager.GetString("UserForm.InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User info update failed!.
        /// </summary>
        internal static string UserForm_UpdateUser_Failed {
            get {
                return ResourceManager.GetString("UserForm.UpdateUser.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User info updated successfully!.
        /// </summary>
        internal static string UserForm_UpdateUser_OK {
            get {
                return ResourceManager.GetString("UserForm.UpdateUser.OK", resourceCulture);
            }
        }
    }
}
